# Generated by Django 3.1.7 on 2021-02-21 13:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('station_type', models.CharField(blank=True, max_length=100, null=True)),
                ('station_type_name', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('transport_type', models.CharField(blank=True, max_length=50, null=True)),
                ('schedule', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Станции',
                'verbose_name_plural': 'Станции',
                'db_table': 'stations',
            },
        ),
    ]
